FROM python:3.9-slim-bullseye

RUN apt update && apt install git curl -y

ARG acapy_url
RUN pip install "aries_cloudagent[askar] @ git+${acapy_url}"

ENTRYPOINT ["/bin/bash", "-c", "aca-py \"$@\"", "--"]
