FROM python:3.12-slim-bullseye

RUN apt clean
RUN apt update && apt install git curl -y

ARG acapy_url
RUN pip install "acapy-agent[askar,didcommv2] @ git+${acapy_url}"

ENTRYPOINT ["/bin/bash", "-c", "aca-py \"$@\"", "--"]
